# Generated by Django 3.1.7 on 2021-02-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('updated_date', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
    ]
