# Generated by Django 3.1.7 on 2021-02-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipID', models.CharField(max_length=100)),
                ('userID', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='name',
            new_name='ship_name',
        ),
    ]
