# Generated by Django 3.1.7 on 2021-02-26 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0003_ship_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='ship_code',
            field=models.CharField(blank=True, default=uuid.UUID('6949b108-389f-4857-9231-9c1c6784f313'), max_length=100, null=True, unique=True),
        ),
    ]
