# Generated by Django 3.1.7 on 2021-02-26 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0004_ship_ship_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='ship_code',
            field=models.CharField(blank=True, default=uuid.UUID('c8ed22aa-9863-4b60-8435-425af6ed41cc'), max_length=100, null=True, unique=True),
        ),
    ]
