# Generated by Django 3.1.7 on 2021-02-27 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('ship', '0005_auto_20210226_0828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserShip',
        ),
        migrations.AddField(
            model_name='ship',
            name='characters',
            field=models.ManyToManyField(to='users.Character'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='ship_code',
            field=models.CharField(blank=True, default=uuid.UUID('d8824c38-8bb8-4f69-97ed-d6f4542d2746'), max_length=100, null=True, unique=True),
        ),
    ]
